site_name: Sample Document
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.expand

nav:
  - Introduction:
    - index.md
  - MkDocs Sample:
    - topic1/index.en.md
    - topic1/page1.en.md

plugins:
  - search:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          site_name: サンプルドキュメント
          Introduction: はじめに
          MkDocs Sample: MkDocsのサンプル

markdown_extensions:
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
    - plantuml_markdown:
        server: http://www.plantuml.com/plantuml
    - admonition
    - pymdownx.superfences
    - pymdownx.details
