name: MkDocsTest

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: build-mkdocs
        run: |
          python -m pip install mkdocs mkdocs-material pygments plantuml_markdown mkdocs-static-i18n mike
          mkdocs build --clean
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
