name: MkDocsTest

on: 
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: build-mkdocs
        env:
          REF: ${{ github.ref }}
        run: |
          python -m pip install mkdocs mkdocs-material pygments plantuml_markdown mkdocs-static-i18n mike
          git config --local user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          mike deploy `echo "${REF##*/}"`
          git checkout gh-pages
          cat .git/config
          git push origin gh-pages
#      - uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_branch: gh-pages
